spring:
  datasource:
    url: jdbc:h2:mem:hambomb;MODE=MYSQL;
    driver-class-name: org.h2.Driver
    username:
    password:
  application:
    name: phones-sample-example
  batch:
    job:
      enabled: false

server:
  port: 9999

mybatis:
  executor-type: batch
